spring:
  artemis:
    broker-url: "tcp://localhost:61616"
    mode: native
    user: artemis
    password: admin
    embedded:
      enabled: false
  jms:
    template:
      default-destination: aa.test.queue